### ISSUE TITLE
Add a guide on the MS Project import

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#3090]
Buld it based on readme file shipped with the demo and add this info 
```
Bryntum Gantt imports the following entities from MS Project:
- tasks
    attributes:
    - id
    - name
    - start date
    - finish date
    - duration
    - duration unit
    - work
    - work unit
    - calendar
    - % complete
    - rollup
    - mode
    - type
    - constraint date
    - constraint type
    - children
    - expanded
- calendars (including project, task and resource calendars)
    - Bryntum Gantt uses a different calendars structure yet it supports importing of all the calendar settings from MS Project
- resources and their assignments to tasks
    attributes:
    - id
    - name
    - calendar
- dependencies (links connecting tasks)
    attributes:
    - id
    - successor
    - predecessor
    - lag
    - lag unit
    - type
- columns
    Bryntum Gantt supports importing of the following columns:
    - Task Name
    - Duration
    - Scheduled Duration
    - Start
    - Finish
    - % Complete
    - Resource Names
    - Early Start
    - Early Finish
    - Late Start
    - Late Finish
    - Total Slack
    - Constraint Type
    - Constraint Date
    - Rollup
    - Baseline Start
    - Baseline Finish
    - Work
    - Task Mode
    - Type
```
