### ISSUE TITLE
[REACT] Bryntum Scheduler and AG Grid CSS doesn't work together

### ISSUE THREAD

**Issue by kronaemmanuel** [bryntum/support#7610]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=26482&p=132033#p132033)

https://github.com/kronaemmanuel/gantt-test-case/tree/bryntum-aggrid (Check the `bryntum-aggrid` branch at commit: `6bad9e73a93bf990f64d93b4dd6f5dee406b41be`).

In `theme-dark.css`:
```css
@import "~@bryntum/schedulerpro/schedulerpro.classic-dark.css"; /* COMMENT THIS ROW and it works */
@import "~@ag-grid-community/core/dist/styles/ag-theme-alpine-dark.min.css";

:root {
  --ag-theme: ag-theme-alpine-dark;
  --background-color: #525252;
}
```
Commenting the first line will make AG Grid work but not Bryntum. Including it will make Bryntum work but not AG Grid.

https://github.com/bryntum/support/assets/18748983/b71e21db-abb4-4e4e-919f-70cc5a670999

Workaround:
Workaround is to include Bryntum CSS import in `components/Scheduler/index.scss` file instead of `theme-dark.css`
