### ISSUE TITLE
`position : sticky` Not applying for timerange labels

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8345]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27746&p=139055#p139055)

Hi,
How can I get the labels in time ranges to be sticky to the top when scrolling vertically?

Attached screenshots for reference.
![Screenshot 2024-01-25 at 1.40.00.png](https://forum.bryntum.com/download/file.php?id=26448)
![Screenshot 2024-01-25 at 1.40.05.png](https://forum.bryntum.com/download/file.php?id=26447)
I tried playing around with position sticky and it didn't work.
```CSS
.b-timeline-subgrid div.b-sch-line label {
    position: sticky;
}
```

Thanks!
